# Generated by Django 6.0.3 on 2026-03-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_image_course_price_courseallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
